
### 1. CADASTRAR PET REX

POST http://localhost:8080/v1/pet
Content-Type: application/json

{
  "nome": "Rex",
  "especie_raca": "Shitzu",
  "idade": 5,
  "nome_tutor": "Deiviston Aguena",
  "telefone_tutor": "67999990001",
  "endereco": "Rua Central, 100",
  "historico_observacoes": "Pet saudável",
  "data_cadastro": "2026-10-02"
}

### 2. CADASTRAR PET MEl

POST http://localhost:8080/v1/pet
Content-Type: application/json

{
  "nome": "Mel",
  "especie_raca": "Labrador",
  "idade": 3,
  "nome_tutor": "Marcus Vinícius",
  "telefone_tutor": "67999990002",
  "endereco": "Rua João Pessoa, 325 - Centro",
  "historico_observacoes": "Pet saudável",
  "data_cadastro": "2026-10-02"
}

### 3. LISTAR TODOS OS PETS

GET http://localhost:8080/v1/pet

### 4. BUSCAR PET REX PELO ID

GET http://localhost:8080/v1/pet/1

### 5. ATUALIZAR PET Mel

PUT http://localhost:8080/v1/pet/1
Content-Type: application/json

{
  "nome": "Mel",
  "especie_raca": "Origem Vira Lata",
  "idade": 6,
  "nome_tutor": "Deiviston Aguena",
  "telefone_tutor": "67999990001",
  "endereco": "Rua Central, 100",
  "historico_observacoes": "Atualização de cadastro",
  "data_cadastro": "2026-10-02"
}

### 6. CADASTRAR AGENDAMENTO PARA REX

POST http://localhost:8080/v1/pet/1/agendamento
Content-Type: application/json

{
  "tipo_servico": "Banho",
  "data_horario": "2026-10-05T09:00:00",
  "valor": 60.00,
  "observacao": "Banho completo"
}

### 7. LISTAR TODOS OS AGENDAMENTOS

GET http://localhost:8080/v1/agendamento

### 8. BUSCAR AGENDAMENTO PELO ID

GET http://localhost:8080/v1/agendamento/1

### 9. TENTAR EXCLUIR AGENDAMENTO AINDA AGENDADO

DELETE http://localhost:8080/v1/agendamento/1

### 10. CONCLUIR AGENDAMENTO

PUT http://localhost:8080/v1/agendamento/1
Content-Type: application/json

{
  "pet_id": 1,
  "tipo_servico": "Banho",
  "data_horario": "2026-10-05T09:00:00",
  "valor": 60.00,
  "observacao": "Banho completo",
  "status": "Concluído"
}

### 11. EXCLUIR AGENDAMENTO CONCLUÍDO

DELETE http://localhost:8080/v1/agendamento/1

### 12. TENTAR BUSCAR AGENDAMENTO INEXISTENTE

GET http://localhost:8080/v1/agendamento/9999

### 13. TENTAR CADASTRAR AGENDAMENTO PARA PET INEXISTENTE

POST http://localhost:8080/v1/pet/9999/agendamento
Content-Type: application/json

{
  "tipo_servico": "Banho",
  "data_horario": "2026-10-05T10:00:00",
  "valor": 60.00,
  "observacao": "Teste de pet inexistente"
}

### 14. LISTAR PETS APÓS OS TESTES

GET http://localhost:8080/v1/pet

### 15. EXCLUIR PET THOR

DELETE http://localhost:8080/v1/pet/2

### 16. LISTAR PETS NOVAMENTE

GET http://localhost:8080/v1/pet


### Cadastrar novamente o mesmo pet
POST http://localhost:8080/v1/pet
Content-Type: application/json

{
  "nome": "Mel",
  "especie_raca": "Golden Retriever",
  "idade": 5,
  "nome_tutor": "Deiviston Aguena",
  "telefone_tutor": "67999990001",
  "endereco": "Rua Central, 100",
  "historico_observacoes": "Pet saudável",
  "data_cadastro": "2026-10-02"
}

###


POST http://localhost:8080/v1/pet
Content-Type: application/json

{
  "nome": "Rex",
  "especie_raca": "Golden Retriever",
  "idade": 5,
  "nome_tutor": "Deiviston Aguena",
  "telefone_tutor": "67999990001",
  "endereco": "Rua Central, 100",
  "historico_observacoes": "Pet saudável",
  "data_cadastro": "2026-10-02"
}