### 1. Cadastrar o pet Rex

POST http://localhost:8080/v1/pet
Content-Type: application/json

{
  "nome": "Rex",
  "especie_raca": "Golden Retriever",
  "idade": 5,
  "nome_tutor": "Deiviston Aguena",
  "telefone_tutor": "67999990001",
  "endereco": "Rua Central, 100",
  "historico_observacoes": "Pet saudável",
  "data_cadastro": "2026-10-01"
}

### 2. Cadastrar o pet Thor

POST http://localhost:8080/v1/pet
Content-Type: application/json

{
  "nome": "Thor",
  "especie_raca": "Labrador",
  "idade": 3,
  "nome_tutor": "Marcus Vinícius",
  "telefone_tutor": "67999990002",
  "endereco": "Rua João Pessoa, 325 - Centro",
  "historico_observacoes": "Pet saudável",
  "data_cadastro": "2026-10-01"
}

### 3. Listar todos os pets

GET http://localhost:8080/v1/pet

### 4. Buscar o pet Rex pelo ID

GET http://localhost:8080/v1/pet/1

### 5. Cadastrar um agendamento de banho para Rex

POST http://localhost:8080/v1/pet/1/agendamento
Content-Type: application/json

{
  "tipo_servico": "Banho",
  "data_horario": "2026-10-05T09:00:00",
  "valor": 60.00,
  "observacao": "Banho completo"
}

### Cadastrar agendamento de banho para o pet 1
POST http://localhost:8080/v1/pet/1/agendamento
Content-Type: application/json

{
  "tipo_servico": "Banho",
  "data_horario": "2026-10-05T09:00:00",
  "valor": 60.00,
  "observacao": "Banho completo"
}